Feat/responsive main menu
SalvadorCardona/lacliqueandcollecte pull request #44
Opened 2021-06-10 07:26 UTC by camillejmr

update syntaxe translation

2021-06-10 12:56 UTC, SalvadorCardona requested changes

2021-06-10 12:56 UTC, SalvadorCardona commented on front/src/core/translate.service.ts
> +console.log(translation);
à retirer

2021-06-10 12:56 UTC, SalvadorCardona commented on front/src/modules/dev/components/ui/ui.text.around.component.ts
> +                    {
Trop d'indexation ici de  4

2021-06-10 12:56 UTC, SalvadorCardona commented on front/src/modules/home/components/home.argumentative.component.ts
> +            text:this.trans("home.argumentative.content.arg2"),
Espace après text:

2021-06-10 12:56 UTC, SalvadorCardona commented on front/src/modules/home/components/home.argumentative.component.ts
> +            textlink:this.trans("home.argumentative.text.link.arg2")
espace après :

2021-06-10 12:56 UTC, SalvadorCardona commented on front/src/modules/home/components/home.argumentative.component.ts
> +            link:'/a-propos',
espace après :

2021-06-10 12:56 UTC, SalvadorCardona commented on front/src/modules/partner/components/partner.view.component.ts
> +                ${this.createElement(IconComponent, {color:Color.PRIMARY ,icon: 'telephone'})} : ${this.partnerPost.meta?.phone}
espace après :

2021-06-10 12:56 UTC, SalvadorCardona commented on front/src/modules/partner/components/partner.view.component.ts
> +                ${this.createElement(IconComponent, {color:Color.PRIMARY ,icon: 'facebook'})} : ${this.partnerPost.meta?.facebook}
espace après :

2021-06-10 12:56 UTC, SalvadorCardona commented on front/src/modules/partner/components/partner.view.component.ts
> +                ${this.createElement(IconComponent, {color:Color.PRIMARY ,icon: 'twitter'})} : ${this.partnerPost.meta?.twitter}
espace après :

2021-06-10 12:56 UTC, SalvadorCardona commented on front/src/modules/partner/components/partner.view.component.ts
> +                ${this.createElement(IconComponent, {color:Color.PRIMARY ,icon: 'instagram'})} : ${this.partnerPost.meta?.instagram}
espace après :

2021-06-10 12:56 UTC, SalvadorCardona commented on front/src/modules/partner/components/partner.view.component.ts
> +                ${this.createElement(IconComponent, {color:Color.PRIMARY ,icon: 'geoLat'})} : ${this.partnerPost.meta?.street}, ${this.partnerPost.meta?.cityCode}, ${this.partnerPost.meta?.city}
espace après :

2021-06-10 12:56 UTC, SalvadorCardona commented on front/src/modules/partner/components/partner.view.component.ts
> +                    {icon: 'envelope', type: Color.PRIMARY, label:this.trans("partner.view.presentation.contact.button.label")}
espace après :

2021-06-10 12:56 UTC, SalvadorCardona commented on front/src/modules/shared/components/header/header.mobile.component.ts
> +
Saut de ligne en trop

2021-06-10 12:56 UTC, SalvadorCardona commented on front/src/modules/shared/components/header/header.mobile.component.ts
> +
Saut de ligne en trop

2021-06-10 12:56 UTC, SalvadorCardona commented on front/src/modules/shared/components/header/header.mobile.component.ts
> +                            <li><a href="#">
balise <a> à besoin d'être à la ligne

2021-06-10 12:56 UTC, SalvadorCardona commented on front/src/modules/shared/components/header/header.mobile.component.ts
> +                            <li><a href="#">
balise <a> à besoin d'être à la ligne

2021-06-10 12:56 UTC, SalvadorCardona commented on front/src/modules/shared/components/modal.cart.component.ts
> +          ${this.createElement(ButtonComponent, {type: Color.DARK, label:this.trans("modal.cart.component.button.clear.cart.label")})}
espace après :

2021-06-10 12:56 UTC, SalvadorCardona commented on front/src/modules/shared/components/modal.product.component.ts
> +
Saut de ligne en trop

2021-06-10 13:00 UTC, RomainLongeron commented on front/src/core/configuration.service.ts
> +        console.log(value);
Est ce que le console.log sert de gestion d'erreur ?

2021-06-10 14:43 UTC, RomainLongeron commented on front/src/modules/shared/components/partner/partner.card.component.ts
> +                        label: this.trans('partner.card.component.button.label') ,
espace après la parenthèse

2021-06-11 12:58 UTC, camillejmr commented on front/src/core/configuration.service.ts
> +        console.log(value);
Non, je l'ai supprimé.

2021-06-11 13:23 UTC, RomainLongeron submitted a review, later dismissed

2021-06-11 13:41 UTC, SalvadorCardona approved these changes, later dismissed

2021-06-14 13:25 UTC, RomainLongeron commented on back/src/Infrastructure/Wordpress/Middleware/Formatter/WpQueryFormatter.php
> +            ->setMaxNumPages((int)$data->max_num_pages);
changement dans une autre PR

2021-06-14 15:22 UTC, RomainLongeron approved these changes, later dismissed

2021-06-14 16:49 UTC, merged