refacto icons
SalvadorCardona/lacliqueandcollecte pull request #46
Opened 2021-06-10 12:20 UTC by camillejmr

2021-06-10 12:57 UTC, SalvadorCardona requested changes

2021-06-10 12:57 UTC, SalvadorCardona commented on front/src/modules/partner/components/partner.header.component.ts
> +            <div id="partner-header"
indexation en trop

2021-06-11 13:49 UTC, SalvadorCardona submitted a review, later dismissed

2021-06-11 13:51 UTC, RomainLongeron commented on front/src/modules/shared/components/icon.component.ts
> +
retour à la ligne en trop

2021-06-14 08:30 UTC, RomainLongeron commented on front/src/modules/dev/components/ui/ui.button.component.ts
> +                        `
retour à la ligne

2021-06-14 12:53 UTC, SalvadorCardona submitted a review, later dismissed

2021-06-14 13:00 UTC, RomainLongeron commented on front/src/modules/search/components/search.left.bar.component.ts
> +
retour à la ligne

2021-06-15 09:49 UTC, merged