Feat : partner page visual
SalvadorCardona/lacliqueandcollecte pull request #54
Opened 2021-06-16 13:22 UTC by RomainLongeron

2021-06-21 10:16 UTC, camillejmr commented on front/src/modules/partner-request/components/partner.request.view.component.ts
> +                <h2 class="text-success h1-responsive font-weight-bold text-center my-4">${this.trans("partner.request.form.title")}</h2>
Penses à faire un retour à la ligne quand tu as plus de 3 classes

2021-06-21 10:21 UTC, camillejmr commented on front/src/modules/shared/components/loader.component.ts
> +<<<<<<< HEAD:front/src/modules/shared/components/loader.component.ts
?

2021-06-22 12:47 UTC, camillejmr approved these changes, later dismissed

2021-06-23 14:14 UTC, SalvadorCardona requested changes

2021-06-23 14:14 UTC, SalvadorCardona commented on front/src/modules/partner-request/components/partner.request.view.component.ts
> +    private renderFormInvalid(): TemplateResult|string {
c'est une fonction de render on lui demande que de faire du rendering pas de faire de la logique

2021-06-23 14:14 UTC, SalvadorCardona commented on front/src/modules/partner-request/components/partner.request.view.component.ts
> +                this.loaderService.hide();
this.formSend = true; doit être ici

2021-06-25 09:32 UTC, SalvadorCardona approved these changes, later dismissed

2021-06-25 11:53 UTC, camillejmr commented on front/src/modules/shared/components/button.component.ts
> +
ligne vide en trop ?

2021-06-25 11:56 UTC, camillejmr commented on front/src/modules/partner-request/components/partner.request.view.component.ts
> +
ligne vide ?

2021-06-25 11:56 UTC, camillejmr commented on front/src/modules/partner-request/components/partner.request.view.component.ts
> +
ligne vide ?

2021-06-25 13:59 UTC, SalvadorCardona approved these changes

2021-06-25 13:59 UTC, merged