Feat : close modal when click on icon
SalvadorCardona/lacliqueandcollecte pull request #59
Opened 2021-06-23 15:58 UTC by camillejmr

2021-06-23 16:35 UTC, SalvadorCardona requested changes

2021-06-23 16:35 UTC, SalvadorCardona commented on front/src/modules/shared/components/modal.component.ts
> +        console.log("test");
Log ici

2021-06-24 12:42 UTC, RomainLongeron approved these changes, later dismissed

2021-06-24 13:00 UTC, SalvadorCardona approved these changes

2021-06-24 13:00 UTC, merged